# Generated by Django 3.1.7 on 2021-06-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NgPattern',
            fields=[
                ('hash_key', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('drill_type', models.CharField(max_length=3)),
                ('left_input', models.CharField(max_length=3)),
                ('right_input', models.CharField(max_length=3)),
                ('answer_select', models.CharField(max_length=3)),
                ('keta_fix_left_flg', models.CharField(max_length=3)),
                ('keta_fix_right_flg', models.CharField(max_length=3)),
                ('left_minus_flg', models.CharField(max_length=3)),
                ('right_minus_flg', models.CharField(max_length=3)),
                ('answer_minus_flg', models.CharField(max_length=3)),
                ('mod_select', models.CharField(max_length=3)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ngpattern',
            },
        ),
    ]
