# Generated by Django 3.1.7 on 2021-04-09 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sansudrill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngpattern',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
